"""correção receitas padrão.

Revision ID: 11adb2ee1f30
Revises: 1377867899ec
Create Date: 2026-06-19 10:48:03.497505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11adb2ee1f30'
down_revision = '1377867899ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MODELO_SOLICITACAO_RECEITA', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MODELO_SOLICITACAO_RECEITA', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
