"""CREATE: tabelas iniciais.

Revision ID: 123e45c32420
Revises: 
Create Date: 2026-06-01 15:49:42.445694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123e45c32420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('paciente_cpf', sa.String(length=20), nullable=False),
    sa.Column('data_atendimento', sa.DateTime(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fila_sincronizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.Enum('ATENDIMENTO_FINALIZADO', 'EVOLUCAO_CRIADA', 'PRESCRICAO_CRIADA', 'EXAME_SOLICITADO', 'ATESTADO_GERADO', name='tipoeventosincronizacao'), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PROCESSANDO', 'SINCRONIZADO', 'ERRO', 'CANCELADO', name='statussincronizacao'), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('ultima_tentativa', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_integracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('payload_enviado', sa.JSON(), nullable=True),
    sa.Column('resposta_recebida', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anamneses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('queixa_principal', sa.Text(), nullable=True),
    sa.Column('historia_doenca_atual', sa.Text(), nullable=True),
    sa.Column('antecedentes_pessoais', sa.Text(), nullable=True),
    sa.Column('antecedentes_familiares', sa.Text(), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('medicamentos_em_uso', sa.Text(), nullable=True),
    sa.Column('habitos_de_vida', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.Enum('VISUALIZOU_PRONTUARIO', 'INICIOU_ATENDIMENTO', 'EDITOU_EVOLUCAO', 'FINALIZOU_ATENDIMENTO', 'GEROU_RECEITA', 'GEROU_ATESTADO', 'SINCRONIZOU_SPDATA', name='acaoauditoria'), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('cid_codigo', sa.String(length=20), nullable=True),
    sa.Column('cid_descricao', sa.String(length=255), nullable=True),
    sa.Column('diagnostico_descritivo', sa.Text(), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('ATESTADO', 'DECLARACAO', 'ENCAMINHAMENTO', 'RELATORIO', 'RECEITA', name='tipodocumentomedico'), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('arquivo_pdf', sa.String(length=255), nullable=True),
    sa.Column('assinado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evolucoes_medicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('texto_evolucao', sa.Text(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('medicamento', sa.String(length=255), nullable=False),
    sa.Column('dosagem', sa.String(length=100), nullable=True),
    sa.Column('frequencia', sa.String(length=100), nullable=True),
    sa.Column('duracao', sa.String(length=100), nullable=True),
    sa.Column('orientacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacoes_exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_exame', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SOLICITADO', 'ENVIADO_SPDATA', 'PENDENTE_SINCRONIZACAO', 'CANCELADO', name='statussolicitacaoexame'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evolucoes_medicas_versoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evolucao_id', sa.Integer(), nullable=False),
    sa.Column('texto_anterior', sa.Text(), nullable=False),
    sa.Column('texto_novo', sa.Text(), nullable=False),
    sa.Column('alterado_por', sa.Integer(), nullable=False),
    sa.Column('motivo_alteracao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alterado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['evolucao_id'], ['evolucoes_medicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evolucoes_medicas_versoes')
    op.drop_table('solicitacoes_exames')
    op.drop_table('prescricoes')
    op.drop_table('evolucoes_medicas')
    op.drop_table('documentos_medicos')
    op.drop_table('diagnosticos')
    op.drop_table('auditorias')
    op.drop_table('anamneses')
    op.drop_table('usuarios')
    op.drop_table('logs_integracao')
    op.drop_table('fila_sincronizacao')
    op.drop_table('atendimentos')
    # ### end Alembic commands ###
