"""correção

Revision ID: 1377867899ec
Revises: 8bfd02f33879
Create Date: 2026-06-19 10:30:32.399557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1377867899ec'
down_revision = '8bfd02f33879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spdata_id', sa.Integer(), nullable=False),
    sa.Column('ato', sa.String(length=50), nullable=True),
    sa.Column('codigo_alfanumerico', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('codigo_amb', sa.String(length=100), nullable=True),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.Column('unidade', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('tipo_procedimento', sa.String(length=50), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('metodo', sa.Text(), nullable=True),
    sa.Column('preparacao', sa.Text(), nullable=True),
    sa.Column('coletor', sa.String(length=255), nullable=True),
    sa.Column('entrega', sa.String(length=100), nullable=True),
    sa.Column('recipiente', sa.String(length=255), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=True),
    sa.Column('antibiograma', sa.String(length=20), nullable=True),
    sa.Column('exame_integrado_webservice', sa.String(length=20), nullable=True),
    sa.Column('somente_solicitacao_pep', sa.String(length=20), nullable=True),
    sa.Column('dados_spdata', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exames_ato'), ['ato'], unique=False)
        batch_op.create_index(batch_op.f('ix_exames_codigo_alfanumerico'), ['codigo_alfanumerico'], unique=False)
        batch_op.create_index(batch_op.f('ix_exames_grupo'), ['grupo'], unique=False)
        batch_op.create_index(batch_op.f('ix_exames_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_exames_situacao'), ['situacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_exames_spdata_id'), ['spdata_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_exames_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exames_tipo'))
        batch_op.drop_index(batch_op.f('ix_exames_spdata_id'))
        batch_op.drop_index(batch_op.f('ix_exames_situacao'))
        batch_op.drop_index(batch_op.f('ix_exames_nome'))
        batch_op.drop_index(batch_op.f('ix_exames_grupo'))
        batch_op.drop_index(batch_op.f('ix_exames_codigo_alfanumerico'))
        batch_op.drop_index(batch_op.f('ix_exames_ato'))

    op.drop_table('exames')
    # ### end Alembic commands ###
