"""CREATE TABLE: tables de cruzamento para criação de query.

Revision ID: 13ea78d0faa5
Revises: ab674f6e25b0
Create Date: 2026-06-17 14:33:30.159759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ea78d0faa5'
down_revision = 'ab674f6e25b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MED_ATENDIMENTOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_medico_spdata', sa.Integer(), nullable=False),
    sa.Column('medico', sa.String(length=255), nullable=False),
    sa.Column('data_agenda', sa.DateTime(), nullable=False),
    sa.Column('hora_agenda', sa.Time(), nullable=False),
    sa.Column('id_paciente_spdata', sa.Integer(), nullable=False),
    sa.Column('paciente', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('prontuario', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('EM_ATENDIMENTO', 'ATENDIDO', 'FALTOU', name='status_atendimento'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('faltou_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MED_SPDATA_AGENDA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico', sa.String(length=255), nullable=False),
    sa.Column('data_agenda', sa.DateTime(), nullable=False),
    sa.Column('hora_agenda', sa.Time(), nullable=False),
    sa.Column('paciente', sa.String(length=255), nullable=False),
    sa.Column('id_paciente_spdata', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('prontuario', sa.Integer(), nullable=False),
    sa.Column('atendido_spdata', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MED_SPDATA_AGENDA')
    op.drop_table('MED_ATENDIMENTOS')
    # ### end Alembic commands ###
