"""ADD COLUMN: nome_completo > table usuarios.

Revision ID: 1a0a1932d14f
Revises: 123e45c32420
Create Date: 2026-06-12 15:00:56.438910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0a1932d14f'
down_revision = '123e45c32420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
