"""ADD COLUMN: medico_id for table MODELO_SOLICITACAO_RECEITA.

Revision ID: 1caef28cb72d
Revises: f2a9d7c6e8b1
Create Date: 2026-06-22 16:08:16.681573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1caef28cb72d'
down_revision = 'f2a9d7c6e8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MODELO_SOLICITACAO_RECEITA', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medico_id', sa.Integer(), nullable=True))

    bind = op.get_bind()
    modelo_receita = sa.table(
        'MODELO_SOLICITACAO_RECEITA',
        sa.column('medico_id', sa.Integer)
    )
    usuarios = sa.table(
        'usuarios',
        sa.column('id', sa.Integer),
        sa.column('role', sa.String)
    )

    padroes_existentes = bind.execute(
        sa.select(sa.func.count()).select_from(modelo_receita)
    ).scalar() or 0

    if padroes_existentes:
        medico_id = bind.execute(
            sa.select(usuarios.c.id)
            .where(usuarios.c.role == 'medico')
            .order_by(usuarios.c.id)
            .limit(1)
        ).scalar()

        if medico_id is None:
            raise RuntimeError(
                "Nao foi possivel migrar padroes existentes: nenhum usuario medico encontrado."
            )

        bind.execute(
            modelo_receita.update()
            .where(modelo_receita.c.medico_id.is_(None))
            .values(medico_id=medico_id)
        )

    with op.batch_alter_table('MODELO_SOLICITACAO_RECEITA', schema=None) as batch_op:
        batch_op.alter_column('medico_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_index(batch_op.f('ix_MODELO_SOLICITACAO_RECEITA_medico_id'), ['medico_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_MODELO_SOLICITACAO_RECEITA_medico_id_usuarios',
            'usuarios',
            ['medico_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MODELO_SOLICITACAO_RECEITA', schema=None) as batch_op:
        batch_op.drop_constraint('fk_MODELO_SOLICITACAO_RECEITA_medico_id_usuarios', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_MODELO_SOLICITACAO_RECEITA_medico_id'))
        batch_op.drop_column('medico_id')

    # ### end Alembic commands ###
