"""CREATE TABLE: tabelas de modelos/padrão de receitas.

Revision ID: 8bfd02f33879
Revises: 13ea78d0faa5
Create Date: 2026-06-17 16:33:01.599226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfd02f33879'
down_revision = '13ea78d0faa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MODELO_SOLICITACAO_RECEITA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_modelo', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MEDICAMENTOS_MODELO_RECEITA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_medicamento', sa.String(length=255), nullable=False),
    sa.Column('dosagem', sa.String(length=15), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('id_modelo_solicitacao_receita', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_modelo_solicitacao_receita'], ['MODELO_SOLICITACAO_RECEITA.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MEDICAMENTOS_MODELO_RECEITA')
    op.drop_table('MODELO_SOLICITACAO_RECEITA')
    # ### end Alembic commands ###
