"""ADD COLUMN: cnpj_cpf > table usuarios.

Revision ID: ab674f6e25b0
Revises: 1a0a1932d14f
Create Date: 2026-06-12 16:29:52.866543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab674f6e25b0'
down_revision = '1a0a1932d14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_completo', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('cnpj_cpf', sa.String(length=255), nullable=False))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.drop_column('cnpj_cpf')
        batch_op.drop_column('nome_completo')

    # ### end Alembic commands ###
