"""CREATE TABLE: tabela de médico.

Revision ID: c14ac1d3af8b
Revises: 11adb2ee1f30
Create Date: 2026-06-19 11:01:52.188719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14ac1d3af8b'
down_revision = '11adb2ee1f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('spdata_id', sa.Integer(), nullable=True),
    sa.Column('crm', sa.String(length=20), nullable=False),
    sa.Column('crm_uf', sa.String(length=2), nullable=False),
    sa.Column('rqe', sa.String(length=30), nullable=True),
    sa.Column('especialidade', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicos_spdata_id'), ['spdata_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicos_usuario_id'), ['usuario_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_medicos_spdata_id'))

    op.drop_table('medicos')
    # ### end Alembic commands ###
